const BACKEND_URL = window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1'
    ? 'http://127.0.0.1:5000'
    : 'https://your-render-app-name.onrender.com';
// DOM Elements
const generateBtn = document.getElementById('generateBtn');
const terminalContainer = document.getElementById('terminalContainer');
const terminalOutput = document.getElementById('terminalOutput');
const resultContainer = document.getElementById('resultContainer');
const markdownOutput = document.getElementById('markdownOutput');

// Placeholder for your Gemini API Key


// Terminal simulation logs
const loadingSteps = [
    "[SYSTEM] Initiating sequence...",
    "[SYSTEM] Analyzing project requirements...",
    "[SYSTEM] Evaluating scalability constraints...",
    "[SYSTEM] Designing monolithic vs microservices approach...",
    "[SYSTEM] Selecting optimal tech stack components...",
    "[SYSTEM] Structuring database schema relationships...",
    "[SYSTEM] Defining core RESTful API endpoints...",
    "[SYSTEM] Drafting deployment and CI/CD strategy...",
    "[SYSTEM] Finalizing architecture blueprint..."
];

generateBtn.addEventListener('click', async () => {
    const desc = document.getElementById('projectDesc').value;
    const scale = document.getElementById('expectedScale').value;

    if (!desc.trim()) {
        alert("Please enter a project description.");
        return;
    }

      // Clear saved project persistence so refresh doesn't re-render old project
    localStorage.removeItem('openProjectIndex');
// 1. Hide and COMPLETELY CLEAR previous results
    resultContainer.classList.add('hidden');
    markdownOutput.innerHTML = ''; // Wipe old text
    
    const complexityContainer =
        document.getElementById('complexityContainer');

    if (complexityContainer) {
        complexityContainer.classList.add('hidden');
}
    const learningHub = document.getElementById('learningHubContainer');
    if(learningHub) learningHub.classList.add('hidden'); // Hide old videos
    
    const mermaidContainer = document.getElementById('mermaidContainer');
    if(mermaidContainer) {
        mermaidContainer.classList.add('hidden'); // Hide old diagram
        mermaidContainer.innerHTML = ''; // Wipe old diagram drawing
    }
    const costContainer = document.getElementById('costEstimatorContainer');
    if(costContainer) costContainer.classList.add('hidden'); // Hide old cost estimator
    // 2. Show terminal and start loading
    terminalContainer.classList.remove('hidden');
    terminalOutput.innerHTML = '';
    generateBtn.disabled = true;
    generateBtn.textContent = 'Architecting...';

    // Simulate terminal logging
    await simulateTerminalLogs();

    // Call the AI
    await fetchArchitecture(desc, scale);
});

// Function to simulate terminal loading steps
function simulateTerminalLogs() {
    return new Promise((resolve) => {
        let step = 0;
        const interval = setInterval(() => {
            if (step < loadingSteps.length) {
                const p = document.createElement('p');
                p.className = 'log-line';
                p.textContent = loadingSteps[step];
                terminalOutput.appendChild(p);
                terminalOutput.scrollTop = terminalOutput.scrollHeight;
                step++;
            } else {
                clearInterval(interval);
                setTimeout(resolve, 500); // small pause after logs finish
            }
        }, 600); // Wait 600ms between each log
    });
}

// Function to call the AI API
async function fetchArchitecture(description, scale) {

    try {

        // CONNECT TO FLASK BACKEND INSTEAD OF GEMINI DIRECTLY
       const controller = new AbortController();

const timeoutId = setTimeout(() => {
    controller.abort();
}, 30000); // 30 seconds timeout

const response = await fetch(`${BACKEND_URL}/generate`, {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json'
    },
    body: JSON.stringify({
        description: description,
        scale: scale
    }),
    signal: controller.signal
});

clearTimeout(timeoutId);

        // HANDLE BACKEND ERRORS
        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }

        const data = await response.json();
        const badge = document.getElementById('generationBadge');
      if (data.fallback) {

    badge.classList.remove('hidden');
    badge.className = 'badge-fallback';
    badge.textContent = '⚠ Generated using Offline Fallback';

    terminalOutput.innerHTML += `
        <p class="log-line" style="color:#ffbd2e;">
            [SYSTEM] AI temporarily unavailable. Showing smart cached architecture sample.
        </p>
    `;

} else {

    badge.classList.remove('hidden');
    badge.className = 'badge-ai';
    badge.textContent = '🤖 Generated by Gemini AI';

}
        // HANDLE CUSTOM BACKEND ERRORS
        if (!data.success) {
            throw new Error(data.error || "Failed to generate architecture");
        }

        const aiText = data.response;
        // SAVE TO LOCAL STORAGE

const savedProjects =
    JSON.parse(
        localStorage.getItem('savedProjects')
    ) || [];

savedProjects.unshift({
    title: description.substring(0, 50),
    content: aiText,
    date: new Date().toLocaleString()
});

localStorage.setItem(
    'savedProjects',
    JSON.stringify(savedProjects)
);
        // --- 1. GUARDRAIL CHECK LOGIC ---
        if (aiText.includes('ERROR_OUT_OF_CONTEXT')) {

            terminalContainer.classList.add('hidden');
            resultContainer.classList.remove('hidden');

            // Hide extra feature boxes
            if (document.getElementById('mermaidContainer')) {
                document.getElementById('mermaidContainer').classList.add('hidden');
            }

            if (document.getElementById('learningHubContainer')) {
                document.getElementById('learningHubContainer').classList.add('hidden');
            }

            if (document.getElementById('costEstimatorContainer')) {
                document.getElementById('costEstimatorContainer').classList.add('hidden');
            }

            // Show apology box
            markdownOutput.innerHTML = `
                <div style="text-align: center; padding: 3rem; background-color: rgba(255, 95, 86, 0.1); border: 1px dashed #ff5f56; border-radius: 8px;">
                    <h2 style="color: #ff5f56; margin-bottom: 1rem;">⚠️ Out of Context</h2>
                    <p style="color: var(--text-muted); font-size: 1.1rem; line-height: 1.6;">
                        Sorry, that is out of what I can do. I only generate system architectures for software, apps, and technical domains. Please enter a valid tech project idea.
                    </p>
                </div>
            `;

            return;
        }

        // --- 2. MERMAID EXTRACTION LOGIC ---
        const mermaidRegex = /``` ?mermaid\n([\s\S]*?)```/;
        const match = aiText.match(mermaidRegex);

        let cleanText = aiText;

        const mermaidContainer = document.getElementById('mermaidContainer');

        if (match) {

            const mermaidCode = match[1];

            cleanText = aiText.replace(mermaidRegex, '');

            mermaidContainer.classList.remove('hidden');

            mermaid.initialize({
                startOnLoad: false,
                theme: 'dark',
                flowchart: { htmlLabels: false }
            });

            try {

                const { svg } = await mermaid.render(
                    'archGraph_' + Date.now(),
                    mermaidCode
                );

                mermaidContainer.innerHTML = svg;

                const svgElement = mermaidContainer.querySelector('svg');

                if (svgElement) {
                    svgElement.style.maxWidth = "100%";
                    svgElement.style.height = "auto";

                    svgElement.removeAttribute("width");
                    svgElement.removeAttribute("height");
                }
                

            } catch (err) {

                console.error("Mermaid error:", err);

                mermaidContainer.innerHTML =
                    "<p style='color: var(--text-muted);'>Diagram could not be rendered.</p>";
            }

        } else {

            mermaidContainer.classList.add('hidden');
            mermaidContainer.innerHTML = "";
        }

        // --- 3. UPDATE UI ---
        terminalContainer.classList.add('hidden');
        resultContainer.classList.remove('hidden');
        

        markdownOutput.innerHTML = DOMPurify.sanitize(marked.parse(cleanText));
        
        // --- 4. EXTRA FEATURES ---
        generateLearningResources(cleanText);
        calculateCostEstimator(cleanText);
        calculateComplexity(cleanText);

    } catch (error) {
        console.error("Error generating architecture:", error);

// TIMEOUT / NO INTERNET / FETCH FAILED
if (
    error.name === 'AbortError' ||
    error.message.includes('Failed to fetch') ||
    error.message.includes('NetworkError')
) {

    terminalOutput.innerHTML += `
        <p class="log-line" style="color: #ffbd2e;">
            [SYSTEM] AI unavailable. Loading cached fallback architecture...
        </p>
    `;

    // CALL BACKEND FALLBACK DIRECTLY
   const fallbackResponse = await fetch(`${BACKEND_URL}/fallback`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({
            description: description,
            scale: scale
        })
    });

    const fallbackData = await fallbackResponse.json();
    const badge = document.getElementById('generationBadge');

badge.classList.remove('hidden');
badge.className = 'badge-fallback';
badge.textContent = '⚠ Generated using Offline Fallback';
const aiText = fallbackData.response;
const savedProjects =
    JSON.parse(
        localStorage.getItem('savedProjects')
    ) || [];

savedProjects.unshift({
    title: description.substring(0, 50),
    content: aiText,
    date: new Date().toLocaleString()
});

localStorage.setItem(
    'savedProjects',
    JSON.stringify(savedProjects)
);
// ===== MERMAID EXTRACTION =====
const mermaidRegex = /``` ?mermaid\n([\s\S]*?)```/;
const match = aiText.match(mermaidRegex);

let cleanText = aiText;

const mermaidContainer = document.getElementById('mermaidContainer');

if (match) {

    const mermaidCode = match[1];

    cleanText = aiText.replace(mermaidRegex, '');

    mermaidContainer.classList.remove('hidden');

    mermaid.initialize({
        startOnLoad: false,
        theme: 'dark',
        flowchart: { htmlLabels: false }
    });

    try {

        const { svg } = await mermaid.render(
            'fallbackGraph_' + Date.now(),
            mermaidCode
        );

        mermaidContainer.innerHTML = svg;

        const svgElement = mermaidContainer.querySelector('svg');

        if (svgElement) {

    svgElement.style.maxWidth = "100%";
    svgElement.style.height = "auto";

    svgElement.removeAttribute("width");
    svgElement.removeAttribute("height");
}

    } catch (err) {

        console.error("Mermaid error:", err);

        mermaidContainer.innerHTML =
            "<p style='color: var(--text-muted);'>Diagram could not be rendered.</p>";
    }

} else {

    mermaidContainer.classList.add('hidden');
    mermaidContainer.innerHTML = "";
}

// ===== SHOW RESULT =====
terminalContainer.classList.add('hidden');
resultContainer.classList.remove('hidden');

markdownOutput.innerHTML = DOMPurify.sanitize(
    marked.parse(cleanText)
);

// ===== EXTRA FEATURES =====
generateLearningResources(cleanText);
calculateCostEstimator(cleanText);
calculateComplexity(cleanText);
} else {

    terminalOutput.innerHTML += `
        <p class="log-line" style="color: #ff5f56; font-weight: bold;">
            [ERROR] System Failure: ${error.message}
        </p>
    `;
}
        
    } finally {

        generateBtn.disabled = false;
        generateBtn.textContent = 'Generate Architecture';
    }
}
// --- 1. SIDEBAR TAB LOGIC ---
const menuItems = document.querySelectorAll('#sidebarMenu li');
const tabContents = document.querySelectorAll('.tab-content');

menuItems.forEach(item => {
    item.addEventListener('click', () => {
        menuItems.forEach(i => i.classList.remove('active'));
        item.classList.add('active');

        tabContents.forEach(tab => tab.classList.remove('active', 'hidden'));
        tabContents.forEach(tab => tab.classList.add('hidden'));

        const targetId = item.getAttribute('data-target');
        document.getElementById(targetId).classList.remove('hidden');
        document.getElementById(targetId).classList.add('active');

        // PERSISTENCE: save which tab is active
        localStorage.setItem('activeTab', targetId);

        // PERSISTENCE: if user manually navigates away from new-arch tab,
        // clear any open project so Case 2 (back to list) works correctly
        if (targetId !== 'tab-new') {
            localStorage.removeItem('openProjectIndex');
        }
    });
});
// --- 2. PDF DOWNLOAD LOGIC ---
const downloadPdfBtn = document.getElementById('downloadPdfBtn');

if (downloadPdfBtn) {
    downloadPdfBtn.addEventListener('click', async () => {
        const element = document.getElementById('pdfExportArea');
        
        const originalText = downloadPdfBtn.textContent;
        downloadPdfBtn.textContent = "Packaging PDF...";
        downloadPdfBtn.disabled = true;
        
        window.scrollTo(0, 0);

        // --- THE DEFINITIVE SVG PIXEL-LOCK FIX ---
        const svgNode = document.querySelector('#mermaidContainer svg');
        let oldWidth = '';
        let oldHeight = '';

        if (svgNode) {
            // 1. Save the original responsive styles
            oldWidth = svgNode.style.width || svgNode.getAttribute('width');
            oldHeight = svgNode.style.height || svgNode.getAttribute('height');

            // 2. html2canvas goes completely blind if an SVG width is "100%". 
            // We must measure it and lock it to exact physical pixels for 1 second!
            const rect = svgNode.getBoundingClientRect();
            svgNode.setAttribute('width', rect.width + 'px');
            svgNode.setAttribute('height', rect.height + 'px');
            svgNode.style.width = rect.width + 'px';
            svgNode.style.height = rect.height + 'px';
        }

        const opt = {
            margin:       10,
            filename:     'Idea2infra_Architecture_Plan.pdf',
            image:        { type: 'jpeg', quality: 0.98 },
            html2canvas:  { 
                scale: 2, 
                useCORS: true, 
                backgroundColor: '#0f172a',
                scrollY: 0
            },
            jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' },
            pagebreak:    { mode: ['css', 'legacy'] } 
        };

        try {
            await html2pdf().set(opt).from(element).save();
        } catch (err) {
            console.error("PDF Generation Error:", err);
        } finally {
            // 3. Put the original responsive styles back so the website doesn't break!
            if (svgNode) {
                svgNode.setAttribute('width', oldWidth || '100%');
                svgNode.setAttribute('height', oldHeight || 'auto');
                svgNode.style.width = oldWidth || '100%';
                svgNode.style.height = oldHeight || 'auto';
            }
            downloadPdfBtn.textContent = originalText;
            downloadPdfBtn.disabled = false;
        }
    });
}
// --- 3. DYNAMIC LEARNING HUB LOGIC ---
const resourceDictionary = {
    "HTML": "https://www.youtube.com/results?search_query=HTML+crash+course+for+beginners",
    "CSS": "https://www.youtube.com/results?search_query=CSS+crash+course",
    "JavaScript": "https://www.youtube.com/results?search_query=Vanilla+JavaScript+tutorial",
    "React": "https://www.youtube.com/results?search_query=React+js+crash+course+for+beginners",
    "Node.js": "https://www.youtube.com/results?search_query=Node.js+express+backend+tutorial",
    "Python": "https://www.youtube.com/results?search_query=Python+backend+api+tutorial",
    "Firebase": "https://www.youtube.com/results?search_query=Firebase+web+setup+tutorial",
    "PostgreSQL": "https://www.youtube.com/results?search_query=PostgreSQL+tutorial+for+beginners",
    "MongoDB": "https://www.youtube.com/results?search_query=MongoDB+crash+course",
    "AWS": "https://www.youtube.com/results?search_query=AWS+architecture+for+beginners",
    "Flutter": "https://www.youtube.com/results?search_query=Flutter+app+development+tutorial",
    "Docker": "https://www.youtube.com/results?search_query=Docker+in+100+seconds",
    "Supabase": "https://www.youtube.com/results?search_query=Supabase+tutorial",
    "Vercel": "https://www.youtube.com/results?search_query=Vercel+deployment+tutorial",
    "GitHub Actions": "https://www.youtube.com/results?search_query=GitHub+Actions+tutorial",
    "CI/CD": "https://www.youtube.com/results?search_query=CI+CD+tutorial",
    "Netlify": "https://www.youtube.com/results?search_query=Netlify+deployment+tutorial",
    "REST API": "https://www.youtube.com/results?search_query=REST+API+tutorial",
    "SQLite": "https://www.youtube.com/results?search_query=SQLite+tutorial",
    "Express": "https://www.youtube.com/results?search_query=Express+js+tutorial"
};

function generateLearningResources(aiText) {

    const learningHubContainer =
        document.getElementById('learningHubContainer');

    const learningLinks =
        document.getElementById('learningLinks');

    // Clear previous links
    learningLinks.innerHTML = '';

    let foundResources = false;

    const addedResources = new Set();

    // If React is recommended,
    // automatically suggest frontend basics too
    if (aiText.toLowerCase().includes('react')) {

        const frontendBasics = [
            'HTML',
            'CSS',
            'JavaScript'
        ];

        frontendBasics.forEach(tech => {

            if (
                resourceDictionary[tech] &&
                !addedResources.has(tech)
            ) {

                const a =
                    document.createElement('a');

                a.href =
                    resourceDictionary[tech];

                a.target = "_blank";

                a.className =
                    "resource-chip";

                a.innerHTML =
                    `▶️ Learn ${tech}`;

                learningLinks.appendChild(a);

                addedResources.add(tech);

                foundResources = true;
            }
        });
    }

    // Check AI output for all technologies
    for (const [tech, link] of Object.entries(resourceDictionary)) {

        if (
            aiText.toLowerCase()
                .includes(tech.toLowerCase())
            &&
            !addedResources.has(tech)
        ) {

            const a =
                document.createElement('a');

            a.href = link;

            a.target = "_blank";

            a.className =
                "resource-chip";

            a.innerHTML =
                `▶️ Learn ${tech}`;

            learningLinks.appendChild(a);

            addedResources.add(tech);

            foundResources = true;
        }
    }

    // Show or hide the learning section
    if (foundResources) {

        learningHubContainer
            .classList.remove('hidden');

    } else {

        learningHubContainer
            .classList.add('hidden');
    }
}
function calculateComplexity(aiText) {

    let score = 1;

    const text = aiText.toLowerCase();

    if (text.includes("react")) score += 1;
    if (text.includes("node")) score += 1;
    if (text.includes("postgresql")) score += 1;
    if (text.includes("firebase")) score += 1;
    if (text.includes("supabase")) score += 1;
    if (text.includes("docker")) score += 1;
    if (text.includes("aws")) score += 2;
    if (text.includes("microservices")) score += 2;
    if (text.includes("kubernetes")) score += 2;

    if (score > 10) score = 10;

    let label = "Beginner Friendly";

    if (score >= 4 && score <= 6) {
        label = "Intermediate";
    }

    if (score >= 7) {
        label = "Advanced Architecture";
    }

    document.getElementById('complexityContainer')
        .classList.remove('hidden');

    document.getElementById('complexityScore')
        .textContent = `${score}/10`;

    document.getElementById('complexityLabel')
        .textContent = label;
}
// --- 4. INTERACTIVE COST ESTIMATOR LOGIC ---
const costEstimatorContainer = document.getElementById('costEstimatorContainer');
const userSlider = document.getElementById('userSlider');
const userCountDisplay = document.getElementById('userCountDisplay');
const totalCostDisplay = document.getElementById('totalCostDisplay');
const costDisclaimer = document.getElementById('costDisclaimer');

let currentCostPerUser = 0.00; // Default base rate
let currentBaseFee = 0;

function calculateCostEstimator(aiText) {
    // 1. Determine the "Tier" based on AI keywords
    const textLower = aiText.toLowerCase();
    
    if (textLower.includes('aws') || textLower.includes('microservices') || textLower.includes('kubernetes')) {
        // Enterprise Tier (Expensive)
        currentCostPerUser = 0.05; 
        currentBaseFee = 150; // Minimum cost for load balancers, RDS, etc.
        costDisclaimer.textContent = "*Base rate: Enterprise Cloud (AWS/GCP) + Managed DBs";
    } 
    else if (textLower.includes('firebase') || textLower.includes('supabase') || textLower.includes('baas')) {
        // Startup Tier (BaaS)
        currentCostPerUser = 0.01;
        currentBaseFee = 25; // Small fixed cost for pro plans
        costDisclaimer.textContent = "*Base rate: Managed BaaS (Firebase/Supabase)";
    } 
    else {
        // Static/MVP Tier (Very Cheap)
        currentCostPerUser = 0.001;
        currentBaseFee = 5; // Basically just domain and basic CDN
        costDisclaimer.textContent = "*Base rate: Static Hosting (Vercel/Netlify) + Serverless";
    }

    // 2. Unhide the widget
    costEstimatorContainer.classList.remove('hidden');
    
    // 3. Trigger the math calculation immediately to show the initial value
    updateCostDisplay();
}

// Math function to update the DOM
function updateCostDisplay() {
    const users = parseInt(userSlider.value);
    userCountDisplay.textContent = users.toLocaleString(); // Adds the commas (e.g., 10,000)
    
    const totalCost = currentBaseFee + (users * currentCostPerUser);
    totalCostDisplay.textContent = "$" + totalCost.toFixed(2);
}

// Add the event listener so the slider updates the math in real-time
userSlider.addEventListener('input', updateCostDisplay);
// --- 5. BOILERPLATE EXPORTER LOGIC (MIC-DROP FEATURE) ---
const downloadCodeBtn = document.getElementById('downloadCodeBtn');

if (downloadCodeBtn) {
    downloadCodeBtn.addEventListener('click', async () => {
        // Change button text to show it's working
        const originalText = downloadCodeBtn.textContent;
        downloadCodeBtn.textContent = "Packaging Project...";
        downloadCodeBtn.disabled = true;

        try {
            // Initialize a new zip file
            const zip = new JSZip();

            // 1. Create the Frontend Folder
            const frontend = zip.folder("frontend");
            frontend.folder("src"); 
            frontend.folder("public"); 
            
            // Create a standard index.html inside frontend
            frontend.file("index.html", `<!DOCTYPE html>\n<html lang="en">\n<head>\n    <title>idea2infra UI</title>\n</head>\n<body>\n    <h1>Welcome to your new Frontend</h1>\n</body>\n</html>`);
            frontend.file("package.json", `{\n  "name": "frontend-app",\n  "version": "1.0.0",\n  "scripts": {\n    "start": "echo 'Starting frontend...'"\n  }\n}`);

            // 2. Create the Backend Folder
            const backend = zip.folder("backend");
            backend.folder("controllers");
            backend.folder("models");
            backend.folder("routes");
            backend.folder("config"); 

            // Create a standard Node.js server file
            backend.file("server.js", `const express = require('express');\nconst app = express();\nconst PORT = process.env.PORT || 3000;\n\napp.use(express.json());\n\napp.get('/', (req, res) => {\n    res.send('idea2infra Backend API is running!');\n});\n\napp.listen(PORT, () => {\n    console.log(\`Server is running on port \${PORT}\`);\n});`);

            // Create a basic package.json for the backend
            backend.file("package.json", `{\n  "name": "idea2infra-backend",\n  "version": "1.0.0",\n  "main": "server.js",\n  "dependencies": {\n    "express": "^4.18.2",\n    "cors": "^2.8.5",\n    "dotenv": "^16.0.3"\n  }\n}`);

            // 3. Create a master README file in the root directory
            zip.file("README.md", `# System Architecture Starter Code\nThis boilerplate workspace was automatically generated by idea2infra.\n\n## Next Steps\n1. Open the \`frontend\` folder to build your UI.\n2. Open the \`backend\` folder, run \`npm install\`, and start building your APIs!`);

            // 4. Generate the zip file and trigger the download
            const content = await zip.generateAsync({ type: "blob" });
            
            // Create a temporary hidden link to download the blob
            const downloadLink = document.createElement("a");
            downloadLink.href = URL.createObjectURL(content);
            downloadLink.download = "idea2infra_Starter_Workspace.zip";
            downloadLink.click();
            
            // Clean up memory
            URL.revokeObjectURL(downloadLink.href);

        } catch (error) {
            console.error("Error generating zip:", error);
            alert("Failed to generate the starter code.");
        } finally {
            // Reset the button
            downloadCodeBtn.textContent = originalText;
            downloadCodeBtn.disabled = false;
        }
    });
}
// ===== COPY ARCHITECTURE FEATURE =====

const copyBtn = document.getElementById('copyArchitectureBtn');

if (copyBtn) {

    copyBtn.addEventListener('click', async () => {

        try {

            const architectureText =
                document.getElementById('markdownOutput').innerText;

            await navigator.clipboard.writeText(
                architectureText
            );

            const originalText = copyBtn.textContent;

            copyBtn.textContent = "✅ Copied!";

            setTimeout(() => {
                copyBtn.textContent = originalText;
            }, 2000);

        } catch (err) {

            console.error(err);

            alert("Failed to copy architecture.");
        }
    });
}
// ===== DOWNLOAD MERMAID DIAGRAM AS PNG =====

const downloadDiagramBtn = document.getElementById('downloadDiagramBtn');

if (downloadDiagramBtn) {

    downloadDiagramBtn.addEventListener('click', () => {

        const svg = document.querySelector('#mermaidContainer svg');

        if (!svg) {
            alert('No diagram available.');
            return;
        }

        const svgData = new XMLSerializer().serializeToString(svg);

        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');

        const img = new Image();

        img.onload = function () {

            canvas.width = img.width;
            canvas.height = img.height;

            ctx.drawImage(img, 0, 0);

            const pngFile = canvas.toDataURL('image/png');

            const downloadLink = document.createElement('a');

            downloadLink.download = 'architecture_diagram.png';
            downloadLink.href = pngFile;

            downloadLink.click();
        };

        img.src =
            'data:image/svg+xml;base64,' +
            btoa(unescape(encodeURIComponent(svgData)));
    });
}
const promptChips =
    document.querySelectorAll('.prompt-chip');

const projectDesc =
    document.getElementById('projectDesc');
promptChips.forEach(chip => {

    chip.addEventListener('click', () => {

        projectDesc.value =
            chip.dataset.prompt;

        projectDesc.focus();
    });

});
function loadSavedProjects() {

    const container =
        document.getElementById('savedProjectsList');

    const savedProjects =
        JSON.parse(
            localStorage.getItem('savedProjects')
        ) || [];

    if (savedProjects.length === 0) {

        container.innerHTML =
            '<p>No projects saved yet.</p>';

        return;
    }

    container.innerHTML = '';

    savedProjects.forEach((project, index) => {

        const card =
            document.createElement('div');

        card.className = 'saved-project-card';

        card.innerHTML = `
            <h3>${project.title}</h3>
            <p>${project.date}</p>
            <button onclick="viewSavedProject(${index})">
                 Open
            </button>

            <button onclick="deleteProject(${index})">
                Delete
            </button>
        `;

        container.appendChild(card);
    });
}
function viewSavedProject(index) {

    const savedProjects =
        JSON.parse(localStorage.getItem('savedProjects')) || [];

    const project = savedProjects[index];
    if (!project) return;

    // PERSISTENCE: save open project index
    localStorage.setItem('openProjectIndex', index);

    // Extract and render mermaid
    const mermaidRegex = /``` ?mermaid\n([\s\S]*?)```/;
    const match = project.content.match(mermaidRegex);
    let cleanText = project.content;

    const savedMermaidContainer = document.getElementById('savedMermaidContainer');
    savedMermaidContainer.innerHTML = '';

    if (match) {
        const mermaidCode = match[1];
        cleanText = project.content.replace(mermaidRegex, '');

        mermaid.initialize({ startOnLoad: false, theme: 'dark', flowchart: { htmlLabels: false } });

        mermaid.render('savedGraph_' + Date.now(), mermaidCode).then(({ svg }) => {
            savedMermaidContainer.innerHTML = svg;
            const svgElement = savedMermaidContainer.querySelector('svg');
            if (svgElement) {
                svgElement.style.maxWidth = "100%";
                svgElement.style.height = "auto";
                svgElement.removeAttribute("width");
                svgElement.removeAttribute("height");
            }
        });
    }

    document.getElementById('savedMarkdownOutput').innerHTML =
        DOMPurify.sanitize(marked.parse(cleanText));

    // Show project view, hide list view — stay inside tab-saved
    document.getElementById('savedListView').classList.add('hidden');
    document.getElementById('savedProjectView').classList.remove('hidden');
}
window.viewSavedProject = viewSavedProject;
loadSavedProjects();
function deleteProject(index) {

    const savedProjects =
        JSON.parse(
            localStorage.getItem('savedProjects')
        ) || [];

    savedProjects.splice(index, 1);

    localStorage.setItem(
        'savedProjects',
        JSON.stringify(savedProjects)
    );

    loadSavedProjects();
}

window.deleteProject = deleteProject;
const searchBox =
    document.getElementById('searchProjects');

if (searchBox) {

    searchBox.addEventListener('input', () => {

        const query =
            searchBox.value.toLowerCase();

        const cards =
            document.querySelectorAll(
                '.saved-project-card'
            );

        cards.forEach(card => {

            if (
                card.innerText
                    .toLowerCase()
                    .includes(query)
            ) {

                card.style.display = 'block';

            } else {

                card.style.display = 'none';
            }
        });
    });
}
const themeToggleBtn =
    document.getElementById('themeToggleBtn');

if (themeToggleBtn) {

    themeToggleBtn.addEventListener('click', () => {

        document.body.classList.toggle(
            'light-theme'
        );

        if (
            document.body.classList.contains(
                'light-theme'
            )
        ) {

            localStorage.setItem(
                'theme',
                'light'
            );

        } else {

            localStorage.setItem(
                'theme',
                'dark'
            );
        }
    });
}
const savedTheme =
    localStorage.getItem('theme');

if (savedTheme === 'light') {

    document.body.classList.add(
        'light-theme'
    );
}
// ===== PAGE REFRESH PERSISTENCE =====
(function restoreAppState() {
    const activeTab = localStorage.getItem('activeTab');
    const openProjectIndex = localStorage.getItem('openProjectIndex');

    if (!activeTab) return;

    // Restore correct tab
    tabContents.forEach(tab => { tab.classList.remove('active'); tab.classList.add('hidden'); });
    menuItems.forEach(i => i.classList.remove('active'));

    const targetTab = document.getElementById(activeTab);
    if (targetTab) {
        targetTab.classList.remove('hidden');
        targetTab.classList.add('active');
    }

    const matchingItem = document.querySelector(`#sidebarMenu li[data-target="${activeTab}"]`);
    if (matchingItem) matchingItem.classList.add('active');

    // If a saved project was open, re-render it inside tab-saved
    if (activeTab === 'tab-saved' && openProjectIndex !== null) {
        viewSavedProject(parseInt(openProjectIndex, 10));
    }
})();
// Back button: return to saved projects list
document.getElementById('backToListBtn').addEventListener('click', () => {
    localStorage.removeItem('openProjectIndex');
    document.getElementById('savedProjectView').classList.add('hidden');
    document.getElementById('savedListView').classList.remove('hidden');
});
// Copy architecture for saved project view
document.getElementById('savedCopyBtn').addEventListener('click', async () => {
    try {
        const text = document.getElementById('savedMarkdownOutput').innerText;
        await navigator.clipboard.writeText(text);
        const btn = document.getElementById('savedCopyBtn');
        const original = btn.textContent;
        btn.textContent = '✅ Copied!';
        setTimeout(() => btn.textContent = original, 2000);
    } catch (err) {
        alert('Failed to copy.');
    }
});

// Download PDF for saved project view
document.getElementById('savedDownloadPdfBtn').addEventListener('click', async () => {
    const btn = document.getElementById('savedDownloadPdfBtn');
    const original = btn.textContent;
    btn.textContent = 'Packaging PDF...';
    btn.disabled = true;

    const svgNode = document.querySelector('#savedMermaidContainer svg');
    let oldWidth = '', oldHeight = '';
    if (svgNode) {
        const rect = svgNode.getBoundingClientRect();
        oldWidth = svgNode.style.width;
        oldHeight = svgNode.style.height;
        svgNode.setAttribute('width', rect.width + 'px');
        svgNode.setAttribute('height', rect.height + 'px');
        svgNode.style.width = rect.width + 'px';
        svgNode.style.height = rect.height + 'px';
    }

    const opt = {
        margin: 10,
        filename: 'Idea2infra_Saved_Architecture.pdf',
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true, backgroundColor: '#0f172a', scrollY: 0 },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        pagebreak: { mode: ['css', 'legacy'] }
    };

    try {
        await html2pdf().set(opt).from(document.getElementById('savedPdfExportArea')).save();
    } catch (err) {
        console.error('PDF error:', err);
    } finally {
        if (svgNode) {
            svgNode.setAttribute('width', oldWidth || '100%');
            svgNode.setAttribute('height', oldHeight || 'auto');
            svgNode.style.width = oldWidth || '100%';
            svgNode.style.height = oldHeight || 'auto';
        }
        btn.textContent = original;
        btn.disabled = false;
    }
});

// Download diagram for saved project view
document.getElementById('savedDownloadDiagramBtn').addEventListener('click', () => {
    const svg = document.querySelector('#savedMermaidContainer svg');
    if (!svg) { alert('No diagram available.'); return; }

    const svgData = new XMLSerializer().serializeToString(svg);
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    const img = new Image();

    img.onload = function () {
        canvas.width = img.width;
        canvas.height = img.height;
        ctx.drawImage(img, 0, 0);
        const link = document.createElement('a');
        link.download = 'saved_architecture_diagram.png';
        link.href = canvas.toDataURL('image/png');
        link.click();
    };

    img.src = 'data:image/svg+xml;base64,' + btoa(unescape(encodeURIComponent(svgData)));
});